# Generated by Django 4.1.2 on 2023-01-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('O', 'Ocupada')], default='Disponível', help_text='Situaçao da vaga', max_length=15, verbose_name='Situaçao'),
        ),
    ]
