# Generated by Django 4.1.2 on 2023-01-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0002_alter_vaga_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='status',
        ),
    ]
