# Generated by Django 4.1.2 on 2023-01-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField(help_text='Hora de entrada', verbose_name='Entrada')),
                ('saida', models.TimeField(help_text='Hora de saida', verbose_name='Saída')),
                ('valor_pago', models.DecimalField(decimal_places=2, help_text='Valor da estada', max_digits=6, verbose_name='Valor')),
                ('tempo', models.DecimalField(decimal_places=2, help_text='Tempo de permanência', max_digits=6, verbose_name='Tempo')),
                ('funcionario', models.ForeignKey(help_text='Nome do funcionario', on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', verbose_name='Funcionario')),
                ('vaga', models.ForeignKey(help_text='Vaga', on_delete=django.db.models.deletion.CASCADE, to='vaga.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Movimentacao',
                'verbose_name_plural': 'Movimentacoes',
            },
        ),
    ]
