# Generated by Django 4.1.2 on 2023-01-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['entrada'], 'verbose_name': 'Movimentacao', 'verbose_name_plural': 'Movimentacoes'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='situacao',
            field=models.CharField(choices=[('O', 'Ocupado'), ('L', 'Livre'), ('T', '------')], default='L', help_text='Situacão da vaga', max_length=15, verbose_name='Situacão'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='entrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
