# Generated by Django 4.1.2 on 2023-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_alter_movimentacao_options_movimentacao_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='saida',
            field=models.DateField(help_text='Hora de saida', verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='situacao',
            field=models.CharField(choices=[('O', 'Ocupado'), ('L', 'Livre'), ('T', '------')], default='T', help_text='Situacão da vaga', max_length=15, verbose_name='Situacão'),
        ),
    ]
