# Generated by Django 4.1.2 on 2022-12-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientepf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('datanascimento', models.CharField(help_text='Data de nascimento', max_length=8, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Número do CPF', max_length=11, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Clentespf',
            },
        ),
    ]
