# Generated by Django 4.1.2 on 2022-12-17 18:36

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('clientepf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepf',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={'thumbnail': {'crop': True, 'height': 100, 'width': 100}}, verbose_name='Foto'),
        ),
    ]
