# Generated by Django 4.1.2 on 2023-01-18 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(default=1, help_text='Nome do cliente', on_delete=django.db.models.deletion.CASCADE, to='home.pessoa', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
