# Generated by Django 4.1.2 on 2023-01-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=1, help_text='Número do CPF', max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
