# Generated by Django 4.1.2 on 2022-12-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientepj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('datanascimento', models.CharField(help_text='Data de nascimento', max_length=8, verbose_name='Data de Nascimento')),
                ('cnpj', models.CharField(help_text='CNPJ', max_length=15, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Clientepj',
                'verbose_name_plural': 'Clientespj',
            },
        ),
    ]
